version: "2"

services:
  db:
    image: mongo:3.2
    ports:
      - 27017
  app:
    build: .
    image: pepper 
    expose:
      - 9999
    links:
      - db
    volumes:
      - '.:/opt/'
    command: /bin/bash
